name: Makefile CI

on:
  push:
    branches: [ "*-nikander", "nikander" ]
  pull_request:
    branches: [ "main" ]
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install g++

    - name: Build
      run: make

    - name: Move testServer.out to a new directory
      run: |
        mkdir artifact-dir
        mv testServer.out artifact-dir/

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-files
        path: ./artifact-dir

#   test:
#     if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4

#     - name: Download artifacts
#       uses: actions/download-artifact@v4
#       with:
#         name: compiled-files
#         path: ./artifact-dir

#     - name: add permission to execute
#       run: chmod +x ./artifact-dir/testServer.out

#     - name: Start server
#       run: ./artifact-dir/testServer.out test

#     - name: Curl / Test server
#       run: |
#         sleep 3  # Give the server some time to start
#         curl http://localhost:8081/index.html