name: Makefile CI

on:
  push:
    branches: [ "main", "*-nikander", "nikander" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install g++

    - name: Build
      run: make

    - name: Move testServer.out to a new directory
      run: |
        mkdir artifact-dir
        mv testServer.out artifact-dir/

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-files
        path: ./artifact-dir

  test:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: compiled-files
        path: ./artifact-dir

    - name: Start server
      run: ./artifact-dir/testServer.out test

    - name: Curl / Test server
      run: |
        sleep 3  # Give the server some time to start
        curl http://localhost:8081/index.html