name: Makefile CI

on:
  push:
    branches: [ "main", "*-nikander", "nikander" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install g++

    - name: Build
      run: make
